name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        subcommand: ['build', 'clippy', 'test']
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: sudo apt-get install -y libxen-dev

      - run: cargo ${{ matrix.subcommand }}
