name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        subcommand: ['build', 'clippy', 'test']
        rust: ['stable', 'nightly']
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - run: sudo apt-get install -y libxen-dev

      - run: cargo ${{ matrix.subcommand }} -v
